security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
 level:
   io:
     pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: https://quote-service-dev-solstice.cfapps.io/quote
